---
version: '2.1'

services:
  tya-frontend:
    build:
      context: .
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    image: hmctspublic.azurecr.io/sscs/tya-frontend
    ports:
      - 3000:3000
