nodejs:
  applicationPort: 3000
  environment:
    PUBLIC_PROTOCOL: https
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-track-your-appeal-frontend
    REFORM_ENVIRONMENT : preview
    SSCS_API_URL: http://sscs-tribunals-api-aat.service.core-compute-aat.internal
    COOKIE_SECRET:
    NODE_ENV: preview
