nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    REFORM_ENVIRONMENT : preview
    SSCS_API_URL: http://sscs-tribunals-api-aat.service.core-compute-aat.internal
    COOKIE_SECRET:
    NODE_ENV: preview
