version: '3.0'

services:
  smoke-tests:
    image: codeception/codeceptjs:1.2.0
    command: bash -c ' NODE_PATH=. codeceptjs run -c test/e2e/ --grep @smoke --steps --reporter mocha-multi'
    volumes:
      - "../.:/tests"
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-https://localhost:3000}
      OUTPUT_DIR: ${OUTPUT_DIR:-./smoke-output}

  functional-tests:
    image: codeception/codeceptjs:1.2.0
    command: bash -c 'NODE_ENV=testing NODE_PATH=. codeceptjs run -c test/e2e/ --reporter mocha-multi'
    volumes:
      - "../.:/tests"
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-https://localhost:3000}
      OUTPUT_DIR: ${OUTPUT_DIR:-./functional-output}
